services:
  db:
    image: mysql:8.0
    container_name: laravel_db_finals
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_finals
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin_finals
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root    # auto-login username
      PMA_PASSWORD: rootpassword  # auto-login password
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
